### ISSUE TITLE
Не отправляется жалоба на комментарий

### ISSUE THREAD

**Issue by fox0** [andreymal/mini_fiction#9]
Если нажать кнопку "Пожаловаться на комментарий", в появившимся окне в поле "Укажите причину жалобы" ввести пробелы, то ничего не происходит, сервер возвращает ту же форму.

**Comment by andreymal** [comment]
Это норма, пробелы считаются пустотой. Не норма то, что я поленился сделать вывод ошибки об обязательности поля
